version: '2'
services:
    early-breakfast-registry:
        image: jhipster/jhipster-registry:v4.1.1
        volumes:
            - ./central-server-config:/central-config
        # By default the JHipster Registry runs with the "dev" and "native"
        # Spring profiles.
        # "native" profile means the filesystem is used to store data, see
        # http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_SECURITY_USER_PASSWORD=admin
            - JHIPSTER_REGISTRY_PASSWORD=admin
            # SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            # SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://dev.azure.com/makhbouz/Makhbouz/_git/early-breakfast-config
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_USERNAME=sghobreilatta@outlook.com
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_PASSWORD=x4elqgysfayxyq2wpmk3zcqy6bqf6vw5nhoiuvi7qnmg6bi2ln6q
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=/**,sandbox
            - JHIPSTER_LOGGING_LOGSTASH_ENABLED=true
            - JHIPSTER_LOGGING_LOGSTASH_HOST=jhipster-logstash
            - JHIPSTER_METRICS_LOGS_ENABLED=true
            - JHIPSTER_METRICS_LOGS_REPORTFREQUENCY=60
        ports:
            - 8761:8761
